FROM mysql:5.7.20

RUN { \
    echo '[client]'; \
    echo 'default-character-set = utf8mb4'; \
    echo '[mysql]'; \
    echo 'default-character-set = utf8mb4'; \
    echo '[mysqld]'; \
    echo 'character-set-client-handshake = FALSE'; \
    echo 'character-set-server = utf8mb4'; \
    echo 'collation-server =  utf8mb4_unicode_ci'; \
    echo "init_connect='SET NAMES utf8mb4'"; \
} > /etc/mysql/conf.d/charset.cnf

